// <auto-generated />
namespace TestDemoCodeDAL.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addMenuAccessTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMenuAccessTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202312170401272_addMenuAccessTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
